dataset_name: 'discharge_point'
window: 24

detrend: False
scale: True
scaling_axis: 'channels'
scaled_target: True

epochs: 300
batch_size: 32
aggregate_by: ['mean']

model_name: 'brits'
d_hidden: 256